project:
  type: website
  output-dir: docs

website:
  title: "HuiL's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Homework

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



